// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Bookmark {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub title: ::prost::alloc::string::String,
    /// RFC 3339.
    #[prost(string, tag="4")]
    pub created_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateBookmarkRequest {
    #[prost(string, tag="1")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub title: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateBookmarkResponse {
    #[prost(message, optional, tag="1")]
    pub bookmark: ::core::option::Option<Bookmark>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListBookmarksRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListBookmarksResponse {
    #[prost(message, repeated, tag="1")]
    pub bookmarks: ::prost::alloc::vec::Vec<Bookmark>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteBookmarkRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteBookmarkResponse {
}
include!("bookmark.v1.tonic.rs");
// @@protoc_insertion_point(module)