// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: bookmark/v1/bookmark.proto

package bookmarkv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Skayfa/reference-patterns/fullstack/auth/paseto-cross-language/issuer-go/pb/bookmark/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BookmarkServiceName is the fully-qualified name of the BookmarkService service.
	BookmarkServiceName = "bookmark.v1.BookmarkService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BookmarkServiceCreateBookmarkProcedure is the fully-qualified name of the BookmarkService's
	// CreateBookmark RPC.
	BookmarkServiceCreateBookmarkProcedure = "/bookmark.v1.BookmarkService/CreateBookmark"
	// BookmarkServiceListBookmarksProcedure is the fully-qualified name of the BookmarkService's
	// ListBookmarks RPC.
	BookmarkServiceListBookmarksProcedure = "/bookmark.v1.BookmarkService/ListBookmarks"
	// BookmarkServiceDeleteBookmarkProcedure is the fully-qualified name of the BookmarkService's
	// DeleteBookmark RPC.
	BookmarkServiceDeleteBookmarkProcedure = "/bookmark.v1.BookmarkService/DeleteBookmark"
)

// BookmarkServiceClient is a client for the bookmark.v1.BookmarkService service.
type BookmarkServiceClient interface {
	CreateBookmark(context.Context, *connect.Request[v1.CreateBookmarkRequest]) (*connect.Response[v1.CreateBookmarkResponse], error)
	ListBookmarks(context.Context, *connect.Request[v1.ListBookmarksRequest]) (*connect.Response[v1.ListBookmarksResponse], error)
	DeleteBookmark(context.Context, *connect.Request[v1.DeleteBookmarkRequest]) (*connect.Response[v1.DeleteBookmarkResponse], error)
}

// NewBookmarkServiceClient constructs a client for the bookmark.v1.BookmarkService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBookmarkServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BookmarkServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	bookmarkServiceMethods := v1.File_bookmark_v1_bookmark_proto.Services().ByName("BookmarkService").Methods()
	return &bookmarkServiceClient{
		createBookmark: connect.NewClient[v1.CreateBookmarkRequest, v1.CreateBookmarkResponse](
			httpClient,
			baseURL+BookmarkServiceCreateBookmarkProcedure,
			connect.WithSchema(bookmarkServiceMethods.ByName("CreateBookmark")),
			connect.WithClientOptions(opts...),
		),
		listBookmarks: connect.NewClient[v1.ListBookmarksRequest, v1.ListBookmarksResponse](
			httpClient,
			baseURL+BookmarkServiceListBookmarksProcedure,
			connect.WithSchema(bookmarkServiceMethods.ByName("ListBookmarks")),
			connect.WithClientOptions(opts...),
		),
		deleteBookmark: connect.NewClient[v1.DeleteBookmarkRequest, v1.DeleteBookmarkResponse](
			httpClient,
			baseURL+BookmarkServiceDeleteBookmarkProcedure,
			connect.WithSchema(bookmarkServiceMethods.ByName("DeleteBookmark")),
			connect.WithClientOptions(opts...),
		),
	}
}

// bookmarkServiceClient implements BookmarkServiceClient.
type bookmarkServiceClient struct {
	createBookmark *connect.Client[v1.CreateBookmarkRequest, v1.CreateBookmarkResponse]
	listBookmarks  *connect.Client[v1.ListBookmarksRequest, v1.ListBookmarksResponse]
	deleteBookmark *connect.Client[v1.DeleteBookmarkRequest, v1.DeleteBookmarkResponse]
}

// CreateBookmark calls bookmark.v1.BookmarkService.CreateBookmark.
func (c *bookmarkServiceClient) CreateBookmark(ctx context.Context, req *connect.Request[v1.CreateBookmarkRequest]) (*connect.Response[v1.CreateBookmarkResponse], error) {
	return c.createBookmark.CallUnary(ctx, req)
}

// ListBookmarks calls bookmark.v1.BookmarkService.ListBookmarks.
func (c *bookmarkServiceClient) ListBookmarks(ctx context.Context, req *connect.Request[v1.ListBookmarksRequest]) (*connect.Response[v1.ListBookmarksResponse], error) {
	return c.listBookmarks.CallUnary(ctx, req)
}

// DeleteBookmark calls bookmark.v1.BookmarkService.DeleteBookmark.
func (c *bookmarkServiceClient) DeleteBookmark(ctx context.Context, req *connect.Request[v1.DeleteBookmarkRequest]) (*connect.Response[v1.DeleteBookmarkResponse], error) {
	return c.deleteBookmark.CallUnary(ctx, req)
}

// BookmarkServiceHandler is an implementation of the bookmark.v1.BookmarkService service.
type BookmarkServiceHandler interface {
	CreateBookmark(context.Context, *connect.Request[v1.CreateBookmarkRequest]) (*connect.Response[v1.CreateBookmarkResponse], error)
	ListBookmarks(context.Context, *connect.Request[v1.ListBookmarksRequest]) (*connect.Response[v1.ListBookmarksResponse], error)
	DeleteBookmark(context.Context, *connect.Request[v1.DeleteBookmarkRequest]) (*connect.Response[v1.DeleteBookmarkResponse], error)
}

// NewBookmarkServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBookmarkServiceHandler(svc BookmarkServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	bookmarkServiceMethods := v1.File_bookmark_v1_bookmark_proto.Services().ByName("BookmarkService").Methods()
	bookmarkServiceCreateBookmarkHandler := connect.NewUnaryHandler(
		BookmarkServiceCreateBookmarkProcedure,
		svc.CreateBookmark,
		connect.WithSchema(bookmarkServiceMethods.ByName("CreateBookmark")),
		connect.WithHandlerOptions(opts...),
	)
	bookmarkServiceListBookmarksHandler := connect.NewUnaryHandler(
		BookmarkServiceListBookmarksProcedure,
		svc.ListBookmarks,
		connect.WithSchema(bookmarkServiceMethods.ByName("ListBookmarks")),
		connect.WithHandlerOptions(opts...),
	)
	bookmarkServiceDeleteBookmarkHandler := connect.NewUnaryHandler(
		BookmarkServiceDeleteBookmarkProcedure,
		svc.DeleteBookmark,
		connect.WithSchema(bookmarkServiceMethods.ByName("DeleteBookmark")),
		connect.WithHandlerOptions(opts...),
	)
	return "/bookmark.v1.BookmarkService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BookmarkServiceCreateBookmarkProcedure:
			bookmarkServiceCreateBookmarkHandler.ServeHTTP(w, r)
		case BookmarkServiceListBookmarksProcedure:
			bookmarkServiceListBookmarksHandler.ServeHTTP(w, r)
		case BookmarkServiceDeleteBookmarkProcedure:
			bookmarkServiceDeleteBookmarkHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBookmarkServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBookmarkServiceHandler struct{}

func (UnimplementedBookmarkServiceHandler) CreateBookmark(context.Context, *connect.Request[v1.CreateBookmarkRequest]) (*connect.Response[v1.CreateBookmarkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bookmark.v1.BookmarkService.CreateBookmark is not implemented"))
}

func (UnimplementedBookmarkServiceHandler) ListBookmarks(context.Context, *connect.Request[v1.ListBookmarksRequest]) (*connect.Response[v1.ListBookmarksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bookmark.v1.BookmarkService.ListBookmarks is not implemented"))
}

func (UnimplementedBookmarkServiceHandler) DeleteBookmark(context.Context, *connect.Request[v1.DeleteBookmarkRequest]) (*connect.Response[v1.DeleteBookmarkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bookmark.v1.BookmarkService.DeleteBookmark is not implemented"))
}
