// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: example/v1/newsletter.proto

package examplev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Skayfa/reference-patterns/fullstack/rpc/connect-protovalidate-tanstack/server/pb/example/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NewsletterServiceName is the fully-qualified name of the NewsletterService service.
	NewsletterServiceName = "example.v1.NewsletterService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NewsletterServiceSubscribeProcedure is the fully-qualified name of the NewsletterService's
	// Subscribe RPC.
	NewsletterServiceSubscribeProcedure = "/example.v1.NewsletterService/Subscribe"
)

// NewsletterServiceClient is a client for the example.v1.NewsletterService service.
type NewsletterServiceClient interface {
	Subscribe(context.Context, *connect.Request[v1.SubscribeRequest]) (*connect.Response[v1.SubscribeResponse], error)
}

// NewNewsletterServiceClient constructs a client for the example.v1.NewsletterService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNewsletterServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NewsletterServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	newsletterServiceMethods := v1.File_example_v1_newsletter_proto.Services().ByName("NewsletterService").Methods()
	return &newsletterServiceClient{
		subscribe: connect.NewClient[v1.SubscribeRequest, v1.SubscribeResponse](
			httpClient,
			baseURL+NewsletterServiceSubscribeProcedure,
			connect.WithSchema(newsletterServiceMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
	}
}

// newsletterServiceClient implements NewsletterServiceClient.
type newsletterServiceClient struct {
	subscribe *connect.Client[v1.SubscribeRequest, v1.SubscribeResponse]
}

// Subscribe calls example.v1.NewsletterService.Subscribe.
func (c *newsletterServiceClient) Subscribe(ctx context.Context, req *connect.Request[v1.SubscribeRequest]) (*connect.Response[v1.SubscribeResponse], error) {
	return c.subscribe.CallUnary(ctx, req)
}

// NewsletterServiceHandler is an implementation of the example.v1.NewsletterService service.
type NewsletterServiceHandler interface {
	Subscribe(context.Context, *connect.Request[v1.SubscribeRequest]) (*connect.Response[v1.SubscribeResponse], error)
}

// NewNewsletterServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNewsletterServiceHandler(svc NewsletterServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	newsletterServiceMethods := v1.File_example_v1_newsletter_proto.Services().ByName("NewsletterService").Methods()
	newsletterServiceSubscribeHandler := connect.NewUnaryHandler(
		NewsletterServiceSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(newsletterServiceMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	return "/example.v1.NewsletterService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NewsletterServiceSubscribeProcedure:
			newsletterServiceSubscribeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNewsletterServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNewsletterServiceHandler struct{}

func (UnimplementedNewsletterServiceHandler) Subscribe(context.Context, *connect.Request[v1.SubscribeRequest]) (*connect.Response[v1.SubscribeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("example.v1.NewsletterService.Subscribe is not implemented"))
}
