// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=js"
// @generated from file auth/v1/access.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { MethodOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/v1/access.proto.
 */
export const file_auth_v1_access: GenFile = /*@__PURE__*/
  fileDesc("ChRhdXRoL3YxL2FjY2Vzcy5wcm90bxIHYXV0aC52MSJBCgpBY2Nlc3NSdWxlEiMKDG1pbmltdW1fcm9sZRgBIAEoDjINLmF1dGgudjEuUm9sZRIOCgZwdWJsaWMYAiABKAgqOwoEUm9sZRIUChBST0xFX1VOU1BFQ0lGSUVEEAASDQoJUk9MRV9VU0VSEAESDgoKUk9MRV9BRE1JThACOk0KBmFjY2VzcxIeLmdvb2dsZS5wcm90b2J1Zi5NZXRob2RPcHRpb25zGNGGAyABKAsyEy5hdXRoLnYxLkFjY2Vzc1J1bGVSBmFjY2Vzc2IGcHJvdG8z", [file_google_protobuf_descriptor]);

/**
 * Declarative per-RPC ACL, carried by the contract itself. Default-deny:
 * EVERY method must be annotated — either public (the auth surface) or with
 * a minimum role — and a CI test fails the build otherwise.
 *
 * @generated from message auth.v1.AccessRule
 */
export type AccessRule = Message<"auth.v1.AccessRule"> & {
  /**
   * Minimum role required; callers with a higher role pass.
   *
   * @generated from field: auth.v1.Role minimum_role = 1;
   */
  minimumRole: Role;

  /**
   * Explicitly unauthenticated (sign-up, log-in, ...).
   *
   * @generated from field: bool public = 2;
   */
  public: boolean;
};

/**
 * Describes the message auth.v1.AccessRule.
 * Use `create(AccessRuleSchema)` to create a new message.
 */
export const AccessRuleSchema: GenMessage<AccessRule> = /*@__PURE__*/
  messageDesc(file_auth_v1_access, 0);

/**
 * The one place role names exist. Token claims and DB rows store the
 * lower-cased name without the prefix ("user", "admin") — the middlewares
 * map back via "ROLE_" + upper(claim). Enum numbers define the hierarchy:
 * a higher role passes a lower requirement.
 *
 * @generated from enum auth.v1.Role
 */
export enum Role {
  /**
   * @generated from enum value: ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ROLE_USER = 1;
   */
  USER = 1,

  /**
   * @generated from enum value: ROLE_ADMIN = 2;
   */
  ADMIN = 2,
}

/**
 * Describes the enum auth.v1.Role.
 */
export const RoleSchema: GenEnum<Role> = /*@__PURE__*/
  enumDesc(file_auth_v1_access, 0);

/**
 * @generated from extension: auth.v1.AccessRule access = 50001;
 */
export const access: GenExtension<MethodOptions, AccessRule> = /*@__PURE__*/
  extDesc(file_auth_v1_access, 0);

