// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=js"
// @generated from file note/v1/note.proto (package note.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_auth_v1_access } from "../../auth/v1/access_pb.js";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file note/v1/note.proto.
 */
export const file_note_v1_note: GenFile = /*@__PURE__*/
  fileDesc("ChJub3RlL3YxL25vdGUucHJvdG8SB25vdGUudjEiNAoETm90ZRIKCgJpZBgBIAEoCRIMCgR0ZXh0GAIgASgJEhIKCmNyZWF0ZWRfYXQYAyABKAkiLQoRQ3JlYXRlTm90ZVJlcXVlc3QSGAoEdGV4dBgBIAEoCUIKukgHcgUQARj0AyIxChJDcmVhdGVOb3RlUmVzcG9uc2USGwoEbm90ZRgBIAEoCzINLm5vdGUudjEuTm90ZSISChBMaXN0Tm90ZXNSZXF1ZXN0IjEKEUxpc3ROb3Rlc1Jlc3BvbnNlEhwKBW5vdGVzGAEgAygLMg0ubm90ZS52MS5Ob3RlIigKEURlbGV0ZU5vdGVSZXF1ZXN0EhMKAmlkGAEgASgJQge6SARyAhABIhQKEkRlbGV0ZU5vdGVSZXNwb25zZTL3AQoLTm90ZVNlcnZpY2USTQoKQ3JlYXRlTm90ZRIaLm5vdGUudjEuQ3JlYXRlTm90ZVJlcXVlc3QaGy5ub3RlLnYxLkNyZWF0ZU5vdGVSZXNwb25zZSIGirUYAggBEkoKCUxpc3ROb3RlcxIZLm5vdGUudjEuTGlzdE5vdGVzUmVxdWVzdBoaLm5vdGUudjEuTGlzdE5vdGVzUmVzcG9uc2UiBoq1GAIIARJNCgpEZWxldGVOb3RlEhoubm90ZS52MS5EZWxldGVOb3RlUmVxdWVzdBobLm5vdGUudjEuRGVsZXRlTm90ZVJlc3BvbnNlIgaKtRgCCAFiBnByb3RvMw", [file_auth_v1_access, file_buf_validate_validate]);

/**
 * @generated from message note.v1.Note
 */
export type Note = Message<"note.v1.Note"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string text = 2;
   */
  text: string;

  /**
   * RFC 3339.
   *
   * @generated from field: string created_at = 3;
   */
  createdAt: string;
};

/**
 * Describes the message note.v1.Note.
 * Use `create(NoteSchema)` to create a new message.
 */
export const NoteSchema: GenMessage<Note> = /*@__PURE__*/
  messageDesc(file_note_v1_note, 0);

/**
 * @generated from message note.v1.CreateNoteRequest
 */
export type CreateNoteRequest = Message<"note.v1.CreateNoteRequest"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message note.v1.CreateNoteRequest.
 * Use `create(CreateNoteRequestSchema)` to create a new message.
 */
export const CreateNoteRequestSchema: GenMessage<CreateNoteRequest> = /*@__PURE__*/
  messageDesc(file_note_v1_note, 1);

/**
 * @generated from message note.v1.CreateNoteResponse
 */
export type CreateNoteResponse = Message<"note.v1.CreateNoteResponse"> & {
  /**
   * @generated from field: note.v1.Note note = 1;
   */
  note?: Note | undefined;
};

/**
 * Describes the message note.v1.CreateNoteResponse.
 * Use `create(CreateNoteResponseSchema)` to create a new message.
 */
export const CreateNoteResponseSchema: GenMessage<CreateNoteResponse> = /*@__PURE__*/
  messageDesc(file_note_v1_note, 2);

/**
 * @generated from message note.v1.ListNotesRequest
 */
export type ListNotesRequest = Message<"note.v1.ListNotesRequest"> & {
};

/**
 * Describes the message note.v1.ListNotesRequest.
 * Use `create(ListNotesRequestSchema)` to create a new message.
 */
export const ListNotesRequestSchema: GenMessage<ListNotesRequest> = /*@__PURE__*/
  messageDesc(file_note_v1_note, 3);

/**
 * @generated from message note.v1.ListNotesResponse
 */
export type ListNotesResponse = Message<"note.v1.ListNotesResponse"> & {
  /**
   * @generated from field: repeated note.v1.Note notes = 1;
   */
  notes: Note[];
};

/**
 * Describes the message note.v1.ListNotesResponse.
 * Use `create(ListNotesResponseSchema)` to create a new message.
 */
export const ListNotesResponseSchema: GenMessage<ListNotesResponse> = /*@__PURE__*/
  messageDesc(file_note_v1_note, 4);

/**
 * @generated from message note.v1.DeleteNoteRequest
 */
export type DeleteNoteRequest = Message<"note.v1.DeleteNoteRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message note.v1.DeleteNoteRequest.
 * Use `create(DeleteNoteRequestSchema)` to create a new message.
 */
export const DeleteNoteRequestSchema: GenMessage<DeleteNoteRequest> = /*@__PURE__*/
  messageDesc(file_note_v1_note, 5);

/**
 * @generated from message note.v1.DeleteNoteResponse
 */
export type DeleteNoteResponse = Message<"note.v1.DeleteNoteResponse"> & {
};

/**
 * Describes the message note.v1.DeleteNoteResponse.
 * Use `create(DeleteNoteResponseSchema)` to create a new message.
 */
export const DeleteNoteResponseSchema: GenMessage<DeleteNoteResponse> = /*@__PURE__*/
  messageDesc(file_note_v1_note, 6);

/**
 * A user-owned entity, added to demonstrate the "new table" flow: this file
 * plus one goose migration and a handful of sqlc queries are the only
 * hand-written declarations — everything else (Go stubs, typed store, TS
 * types, front hooks, ACL enforcement) is generated or shared.
 *
 * Notes are always scoped to the caller (the token's sub claim): the API
 * never takes a user id. Implemented by the Go server only — it owns the
 * storage; the verifiers have nothing to do with it.
 *
 * @generated from service note.v1.NoteService
 */
export const NoteService: GenService<{
  /**
   * @generated from rpc note.v1.NoteService.CreateNote
   */
  createNote: {
    methodKind: "unary";
    input: typeof CreateNoteRequestSchema;
    output: typeof CreateNoteResponseSchema;
  },
  /**
   * @generated from rpc note.v1.NoteService.ListNotes
   */
  listNotes: {
    methodKind: "unary";
    input: typeof ListNotesRequestSchema;
    output: typeof ListNotesResponseSchema;
  },
  /**
   * The option gates the role; ownership (owner-or-admin) is business logic
   * in the handler — claims are in the context, put there by the middleware.
   *
   * @generated from rpc note.v1.NoteService.DeleteNote
   */
  deleteNote: {
    methodKind: "unary";
    input: typeof DeleteNoteRequestSchema;
    output: typeof DeleteNoteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_note_v1_note, 0);

