// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: demo/v1/protected.proto

package demov1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/Skayfa/reference-patterns/fullstack/auth/paseto-cross-language/issuer-go/pb/demo/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProtectedServiceName is the fully-qualified name of the ProtectedService service.
	ProtectedServiceName = "demo.v1.ProtectedService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProtectedServiceWhoAmIProcedure is the fully-qualified name of the ProtectedService's WhoAmI RPC.
	ProtectedServiceWhoAmIProcedure = "/demo.v1.ProtectedService/WhoAmI"
	// ProtectedServiceAdminOnlyProcedure is the fully-qualified name of the ProtectedService's
	// AdminOnly RPC.
	ProtectedServiceAdminOnlyProcedure = "/demo.v1.ProtectedService/AdminOnly"
)

// ProtectedServiceClient is a client for the demo.v1.ProtectedService service.
type ProtectedServiceClient interface {
	WhoAmI(context.Context, *connect.Request[v1.WhoAmIRequest]) (*connect.Response[v1.WhoAmIResponse], error)
	AdminOnly(context.Context, *connect.Request[v1.AdminOnlyRequest]) (*connect.Response[v1.AdminOnlyResponse], error)
}

// NewProtectedServiceClient constructs a client for the demo.v1.ProtectedService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProtectedServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProtectedServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	protectedServiceMethods := v1.File_demo_v1_protected_proto.Services().ByName("ProtectedService").Methods()
	return &protectedServiceClient{
		whoAmI: connect.NewClient[v1.WhoAmIRequest, v1.WhoAmIResponse](
			httpClient,
			baseURL+ProtectedServiceWhoAmIProcedure,
			connect.WithSchema(protectedServiceMethods.ByName("WhoAmI")),
			connect.WithClientOptions(opts...),
		),
		adminOnly: connect.NewClient[v1.AdminOnlyRequest, v1.AdminOnlyResponse](
			httpClient,
			baseURL+ProtectedServiceAdminOnlyProcedure,
			connect.WithSchema(protectedServiceMethods.ByName("AdminOnly")),
			connect.WithClientOptions(opts...),
		),
	}
}

// protectedServiceClient implements ProtectedServiceClient.
type protectedServiceClient struct {
	whoAmI    *connect.Client[v1.WhoAmIRequest, v1.WhoAmIResponse]
	adminOnly *connect.Client[v1.AdminOnlyRequest, v1.AdminOnlyResponse]
}

// WhoAmI calls demo.v1.ProtectedService.WhoAmI.
func (c *protectedServiceClient) WhoAmI(ctx context.Context, req *connect.Request[v1.WhoAmIRequest]) (*connect.Response[v1.WhoAmIResponse], error) {
	return c.whoAmI.CallUnary(ctx, req)
}

// AdminOnly calls demo.v1.ProtectedService.AdminOnly.
func (c *protectedServiceClient) AdminOnly(ctx context.Context, req *connect.Request[v1.AdminOnlyRequest]) (*connect.Response[v1.AdminOnlyResponse], error) {
	return c.adminOnly.CallUnary(ctx, req)
}

// ProtectedServiceHandler is an implementation of the demo.v1.ProtectedService service.
type ProtectedServiceHandler interface {
	WhoAmI(context.Context, *connect.Request[v1.WhoAmIRequest]) (*connect.Response[v1.WhoAmIResponse], error)
	AdminOnly(context.Context, *connect.Request[v1.AdminOnlyRequest]) (*connect.Response[v1.AdminOnlyResponse], error)
}

// NewProtectedServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProtectedServiceHandler(svc ProtectedServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	protectedServiceMethods := v1.File_demo_v1_protected_proto.Services().ByName("ProtectedService").Methods()
	protectedServiceWhoAmIHandler := connect.NewUnaryHandler(
		ProtectedServiceWhoAmIProcedure,
		svc.WhoAmI,
		connect.WithSchema(protectedServiceMethods.ByName("WhoAmI")),
		connect.WithHandlerOptions(opts...),
	)
	protectedServiceAdminOnlyHandler := connect.NewUnaryHandler(
		ProtectedServiceAdminOnlyProcedure,
		svc.AdminOnly,
		connect.WithSchema(protectedServiceMethods.ByName("AdminOnly")),
		connect.WithHandlerOptions(opts...),
	)
	return "/demo.v1.ProtectedService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProtectedServiceWhoAmIProcedure:
			protectedServiceWhoAmIHandler.ServeHTTP(w, r)
		case ProtectedServiceAdminOnlyProcedure:
			protectedServiceAdminOnlyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProtectedServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProtectedServiceHandler struct{}

func (UnimplementedProtectedServiceHandler) WhoAmI(context.Context, *connect.Request[v1.WhoAmIRequest]) (*connect.Response[v1.WhoAmIResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("demo.v1.ProtectedService.WhoAmI is not implemented"))
}

func (UnimplementedProtectedServiceHandler) AdminOnly(context.Context, *connect.Request[v1.AdminOnlyRequest]) (*connect.Response[v1.AdminOnlyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("demo.v1.ProtectedService.AdminOnly is not implemented"))
}
