// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=js"
// @generated from file auth/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_auth_v1_access } from "./access_pb.js";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/v1/auth.proto.
 */
export const file_auth_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("ChJhdXRoL3YxL2F1dGgucHJvdG8SB2F1dGgudjEiQgoNU2lnblVwUmVxdWVzdBIWCgVlbWFpbBgBIAEoCUIHukgEcgJgARIZCghwYXNzd29yZBgCIAEoCUIHukgEcgIQCCIhCg5TaWduVXBSZXNwb25zZRIPCgd1c2VyX2lkGAEgASgJIkEKDExvZ0luUmVxdWVzdBIWCgVlbWFpbBgBIAEoCUIHukgEcgIQARIZCghwYXNzd29yZBgCIAEoCUIHukgEcgIQASIzCg1Mb2dJblJlc3BvbnNlEiIKBnRva2VucxgBIAEoCzISLmF1dGgudjEuVG9rZW5QYWlyIjAKDlJlZnJlc2hSZXF1ZXN0Eh4KDXJlZnJlc2hfdG9rZW4YASABKAlCB7pIBHICEAEiNQoPUmVmcmVzaFJlc3BvbnNlEiIKBnRva2VucxgBIAEoCzISLmF1dGgudjEuVG9rZW5QYWlyIiYKDUxvZ091dFJlcXVlc3QSFQoNcmVmcmVzaF90b2tlbhgBIAEoCSIQCg5Mb2dPdXRSZXNwb25zZSJTCglUb2tlblBhaXISFAoMYWNjZXNzX3Rva2VuGAEgASgJEhkKEWFjY2Vzc19leHBpcmVzX2F0GAIgASgJEhUKDXJlZnJlc2hfdG9rZW4YAyABKAkymQIKC0F1dGhTZXJ2aWNlEkEKBlNpZ25VcBIWLmF1dGgudjEuU2lnblVwUmVxdWVzdBoXLmF1dGgudjEuU2lnblVwUmVzcG9uc2UiBoq1GAIQARI+CgVMb2dJbhIVLmF1dGgudjEuTG9nSW5SZXF1ZXN0GhYuYXV0aC52MS5Mb2dJblJlc3BvbnNlIgaKtRgCEAESRAoHUmVmcmVzaBIXLmF1dGgudjEuUmVmcmVzaFJlcXVlc3QaGC5hdXRoLnYxLlJlZnJlc2hSZXNwb25zZSIGirUYAhABEkEKBkxvZ091dBIWLmF1dGgudjEuTG9nT3V0UmVxdWVzdBoXLmF1dGgudjEuTG9nT3V0UmVzcG9uc2UiBoq1GAIQAWIGcHJvdG8z", [file_auth_v1_access, file_buf_validate_validate]);

/**
 * @generated from message auth.v1.SignUpRequest
 */
export type SignUpRequest = Message<"auth.v1.SignUpRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message auth.v1.SignUpRequest.
 * Use `create(SignUpRequestSchema)` to create a new message.
 */
export const SignUpRequestSchema: GenMessage<SignUpRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 0);

/**
 * @generated from message auth.v1.SignUpResponse
 */
export type SignUpResponse = Message<"auth.v1.SignUpResponse"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message auth.v1.SignUpResponse.
 * Use `create(SignUpResponseSchema)` to create a new message.
 */
export const SignUpResponseSchema: GenMessage<SignUpResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 1);

/**
 * @generated from message auth.v1.LogInRequest
 */
export type LogInRequest = Message<"auth.v1.LogInRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message auth.v1.LogInRequest.
 * Use `create(LogInRequestSchema)` to create a new message.
 */
export const LogInRequestSchema: GenMessage<LogInRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 2);

/**
 * @generated from message auth.v1.LogInResponse
 */
export type LogInResponse = Message<"auth.v1.LogInResponse"> & {
  /**
   * @generated from field: auth.v1.TokenPair tokens = 1;
   */
  tokens?: TokenPair | undefined;
};

/**
 * Describes the message auth.v1.LogInResponse.
 * Use `create(LogInResponseSchema)` to create a new message.
 */
export const LogInResponseSchema: GenMessage<LogInResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 3);

/**
 * @generated from message auth.v1.RefreshRequest
 */
export type RefreshRequest = Message<"auth.v1.RefreshRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message auth.v1.RefreshRequest.
 * Use `create(RefreshRequestSchema)` to create a new message.
 */
export const RefreshRequestSchema: GenMessage<RefreshRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 4);

/**
 * @generated from message auth.v1.RefreshResponse
 */
export type RefreshResponse = Message<"auth.v1.RefreshResponse"> & {
  /**
   * @generated from field: auth.v1.TokenPair tokens = 1;
   */
  tokens?: TokenPair | undefined;
};

/**
 * Describes the message auth.v1.RefreshResponse.
 * Use `create(RefreshResponseSchema)` to create a new message.
 */
export const RefreshResponseSchema: GenMessage<RefreshResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 5);

/**
 * @generated from message auth.v1.LogOutRequest
 */
export type LogOutRequest = Message<"auth.v1.LogOutRequest"> & {
  /**
   * @generated from field: string refresh_token = 1;
   */
  refreshToken: string;
};

/**
 * Describes the message auth.v1.LogOutRequest.
 * Use `create(LogOutRequestSchema)` to create a new message.
 */
export const LogOutRequestSchema: GenMessage<LogOutRequest> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 6);

/**
 * @generated from message auth.v1.LogOutResponse
 */
export type LogOutResponse = Message<"auth.v1.LogOutResponse"> & {
};

/**
 * Describes the message auth.v1.LogOutResponse.
 * Use `create(LogOutResponseSchema)` to create a new message.
 */
export const LogOutResponseSchema: GenMessage<LogOutResponse> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 7);

/**
 * @generated from message auth.v1.TokenPair
 */
export type TokenPair = Message<"auth.v1.TokenPair"> & {
  /**
   * PASETO v4.public access token ("v4.public...."), short-lived.
   *
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * RFC 3339, verbatim copy of the token's exp claim. PASETO claims are
   * RFC 3339 strings by spec, so no timestamp conversion happens anywhere.
   *
   * @generated from field: string access_expires_at = 2;
   */
  accessExpiresAt: string;

  /**
   * Opaque single-use token: exchanged (and rotated) via Refresh.
   *
   * @generated from field: string refresh_token = 3;
   */
  refreshToken: string;
};

/**
 * Describes the message auth.v1.TokenPair.
 * Use `create(TokenPairSchema)` to create a new message.
 */
export const TokenPairSchema: GenMessage<TokenPair> = /*@__PURE__*/
  messageDesc(file_auth_v1_auth, 8);

/**
 * AuthService is the single token issuer. Only the Go server implements it;
 * every other service just verifies the tokens it emits. The methods are
 * explicitly public: the default-deny gate requires every RPC to declare
 * its access rule, including "none needed".
 *
 * @generated from service auth.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc auth.v1.AuthService.SignUp
   */
  signUp: {
    methodKind: "unary";
    input: typeof SignUpRequestSchema;
    output: typeof SignUpResponseSchema;
  },
  /**
   * @generated from rpc auth.v1.AuthService.LogIn
   */
  logIn: {
    methodKind: "unary";
    input: typeof LogInRequestSchema;
    output: typeof LogInResponseSchema;
  },
  /**
   * @generated from rpc auth.v1.AuthService.Refresh
   */
  refresh: {
    methodKind: "unary";
    input: typeof RefreshRequestSchema;
    output: typeof RefreshResponseSchema;
  },
  /**
   * @generated from rpc auth.v1.AuthService.LogOut
   */
  logOut: {
    methodKind: "unary";
    input: typeof LogOutRequestSchema;
    output: typeof LogOutResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_auth_v1_auth, 0);

