// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=js"
// @generated from file bookmark/v1/bookmark.proto (package bookmark.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_auth_v1_access } from "../../auth/v1/access_pb.js";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file bookmark/v1/bookmark.proto.
 */
export const file_bookmark_v1_bookmark: GenFile = /*@__PURE__*/
  fileDesc("Chpib29rbWFyay92MS9ib29rbWFyay5wcm90bxILYm9va21hcmsudjEiRgoIQm9va21hcmsSCgoCaWQYASABKAkSCwoDdXJsGAIgASgJEg0KBXRpdGxlGAMgASgJEhIKCmNyZWF0ZWRfYXQYBCABKAkiSQoVQ3JlYXRlQm9va21hcmtSZXF1ZXN0EhcKA3VybBgBIAEoCUIKukgHcgUQARiAEBIXCgV0aXRsZRgCIAEoCUIIukgFcgMYyAEiQQoWQ3JlYXRlQm9va21hcmtSZXNwb25zZRInCghib29rbWFyaxgBIAEoCzIVLmJvb2ttYXJrLnYxLkJvb2ttYXJrIhYKFExpc3RCb29rbWFya3NSZXF1ZXN0IkEKFUxpc3RCb29rbWFya3NSZXNwb25zZRIoCglib29rbWFya3MYASADKAsyFS5ib29rbWFyay52MS5Cb29rbWFyayIsChVEZWxldGVCb29rbWFya1JlcXVlc3QSEwoCaWQYASABKAlCB7pIBHICEAEiGAoWRGVsZXRlQm9va21hcmtSZXNwb25zZTK3AgoPQm9va21hcmtTZXJ2aWNlEmEKDkNyZWF0ZUJvb2ttYXJrEiIuYm9va21hcmsudjEuQ3JlYXRlQm9va21hcmtSZXF1ZXN0GiMuYm9va21hcmsudjEuQ3JlYXRlQm9va21hcmtSZXNwb25zZSIGirUYAggBEl4KDUxpc3RCb29rbWFya3MSIS5ib29rbWFyay52MS5MaXN0Qm9va21hcmtzUmVxdWVzdBoiLmJvb2ttYXJrLnYxLkxpc3RCb29rbWFya3NSZXNwb25zZSIGirUYAggBEmEKDkRlbGV0ZUJvb2ttYXJrEiIuYm9va21hcmsudjEuRGVsZXRlQm9va21hcmtSZXF1ZXN0GiMuYm9va21hcmsudjEuRGVsZXRlQm9va21hcmtSZXNwb25zZSIGirUYAggBYgZwcm90bzM", [file_auth_v1_access, file_buf_validate_validate]);

/**
 * @generated from message bookmark.v1.Bookmark
 */
export type Bookmark = Message<"bookmark.v1.Bookmark"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string url = 2;
   */
  url: string;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * RFC 3339.
   *
   * @generated from field: string created_at = 4;
   */
  createdAt: string;
};

/**
 * Describes the message bookmark.v1.Bookmark.
 * Use `create(BookmarkSchema)` to create a new message.
 */
export const BookmarkSchema: GenMessage<Bookmark> = /*@__PURE__*/
  messageDesc(file_bookmark_v1_bookmark, 0);

/**
 * @generated from message bookmark.v1.CreateBookmarkRequest
 */
export type CreateBookmarkRequest = Message<"bookmark.v1.CreateBookmarkRequest"> & {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;
};

/**
 * Describes the message bookmark.v1.CreateBookmarkRequest.
 * Use `create(CreateBookmarkRequestSchema)` to create a new message.
 */
export const CreateBookmarkRequestSchema: GenMessage<CreateBookmarkRequest> = /*@__PURE__*/
  messageDesc(file_bookmark_v1_bookmark, 1);

/**
 * @generated from message bookmark.v1.CreateBookmarkResponse
 */
export type CreateBookmarkResponse = Message<"bookmark.v1.CreateBookmarkResponse"> & {
  /**
   * @generated from field: bookmark.v1.Bookmark bookmark = 1;
   */
  bookmark?: Bookmark | undefined;
};

/**
 * Describes the message bookmark.v1.CreateBookmarkResponse.
 * Use `create(CreateBookmarkResponseSchema)` to create a new message.
 */
export const CreateBookmarkResponseSchema: GenMessage<CreateBookmarkResponse> = /*@__PURE__*/
  messageDesc(file_bookmark_v1_bookmark, 2);

/**
 * @generated from message bookmark.v1.ListBookmarksRequest
 */
export type ListBookmarksRequest = Message<"bookmark.v1.ListBookmarksRequest"> & {
};

/**
 * Describes the message bookmark.v1.ListBookmarksRequest.
 * Use `create(ListBookmarksRequestSchema)` to create a new message.
 */
export const ListBookmarksRequestSchema: GenMessage<ListBookmarksRequest> = /*@__PURE__*/
  messageDesc(file_bookmark_v1_bookmark, 3);

/**
 * @generated from message bookmark.v1.ListBookmarksResponse
 */
export type ListBookmarksResponse = Message<"bookmark.v1.ListBookmarksResponse"> & {
  /**
   * @generated from field: repeated bookmark.v1.Bookmark bookmarks = 1;
   */
  bookmarks: Bookmark[];
};

/**
 * Describes the message bookmark.v1.ListBookmarksResponse.
 * Use `create(ListBookmarksResponseSchema)` to create a new message.
 */
export const ListBookmarksResponseSchema: GenMessage<ListBookmarksResponse> = /*@__PURE__*/
  messageDesc(file_bookmark_v1_bookmark, 4);

/**
 * @generated from message bookmark.v1.DeleteBookmarkRequest
 */
export type DeleteBookmarkRequest = Message<"bookmark.v1.DeleteBookmarkRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message bookmark.v1.DeleteBookmarkRequest.
 * Use `create(DeleteBookmarkRequestSchema)` to create a new message.
 */
export const DeleteBookmarkRequestSchema: GenMessage<DeleteBookmarkRequest> = /*@__PURE__*/
  messageDesc(file_bookmark_v1_bookmark, 5);

/**
 * @generated from message bookmark.v1.DeleteBookmarkResponse
 */
export type DeleteBookmarkResponse = Message<"bookmark.v1.DeleteBookmarkResponse"> & {
};

/**
 * Describes the message bookmark.v1.DeleteBookmarkResponse.
 * Use `create(DeleteBookmarkResponseSchema)` to create a new message.
 */
export const DeleteBookmarkResponseSchema: GenMessage<DeleteBookmarkResponse> = /*@__PURE__*/
  messageDesc(file_bookmark_v1_bookmark, 6);

/**
 * The Rust-owned entity: same shape as note.v1, different owner. The Rust
 * server holds this table in ITS OWN SQLite database (sqlx migrations) —
 * no other service touches it. One owner per table; everyone else goes
 * through this API.
 *
 * Note on validation: the buf.validate rules below are enforced by clients
 * and documented in the contract, but Rust has no first-party protovalidate
 * runtime — the handler enforces them by hand (see PATTERN.md Key points
 * for the switch-over threshold).
 *
 * @generated from service bookmark.v1.BookmarkService
 */
export const BookmarkService: GenService<{
  /**
   * @generated from rpc bookmark.v1.BookmarkService.CreateBookmark
   */
  createBookmark: {
    methodKind: "unary";
    input: typeof CreateBookmarkRequestSchema;
    output: typeof CreateBookmarkResponseSchema;
  },
  /**
   * @generated from rpc bookmark.v1.BookmarkService.ListBookmarks
   */
  listBookmarks: {
    methodKind: "unary";
    input: typeof ListBookmarksRequestSchema;
    output: typeof ListBookmarksResponseSchema;
  },
  /**
   * @generated from rpc bookmark.v1.BookmarkService.DeleteBookmark
   */
  deleteBookmark: {
    methodKind: "unary";
    input: typeof DeleteBookmarkRequestSchema;
    output: typeof DeleteBookmarkResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_bookmark_v1_bookmark, 0);

