// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: demo/v1/protected.proto

package demov1

import (
	_ "github.com/Skayfa/reference-patterns/fullstack/auth/paseto-cross-language/issuer-go/pb/auth/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WhoAmIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIRequest) Reset() {
	*x = WhoAmIRequest{}
	mi := &file_demo_v1_protected_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIRequest) ProtoMessage() {}

func (x *WhoAmIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_protected_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIRequest.ProtoReflect.Descriptor instead.
func (*WhoAmIRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_protected_proto_rawDescGZIP(), []int{0}
}

type WhoAmIResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Subject string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Role    string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	// RFC 3339, echoed verbatim from the token claims.
	IssuedAt  string `protobuf:"bytes,3,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt string `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Which implementation answered: "go-connect" | "rust-tonic" | "ts-connect".
	ServedBy      string `protobuf:"bytes,5,opt,name=served_by,json=servedBy,proto3" json:"served_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_demo_v1_protected_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_protected_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_demo_v1_protected_proto_rawDescGZIP(), []int{1}
}

func (x *WhoAmIResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *WhoAmIResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WhoAmIResponse) GetIssuedAt() string {
	if x != nil {
		return x.IssuedAt
	}
	return ""
}

func (x *WhoAmIResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *WhoAmIResponse) GetServedBy() string {
	if x != nil {
		return x.ServedBy
	}
	return ""
}

type AdminOnlyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminOnlyRequest) Reset() {
	*x = AdminOnlyRequest{}
	mi := &file_demo_v1_protected_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminOnlyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminOnlyRequest) ProtoMessage() {}

func (x *AdminOnlyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_protected_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminOnlyRequest.ProtoReflect.Descriptor instead.
func (*AdminOnlyRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_protected_proto_rawDescGZIP(), []int{2}
}

type AdminOnlyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminOnlyResponse) Reset() {
	*x = AdminOnlyResponse{}
	mi := &file_demo_v1_protected_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminOnlyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminOnlyResponse) ProtoMessage() {}

func (x *AdminOnlyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_protected_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminOnlyResponse.ProtoReflect.Descriptor instead.
func (*AdminOnlyResponse) Descriptor() ([]byte, []int) {
	return file_demo_v1_protected_proto_rawDescGZIP(), []int{3}
}

func (x *AdminOnlyResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_demo_v1_protected_proto protoreflect.FileDescriptor

const file_demo_v1_protected_proto_rawDesc = "" +
	"\n" +
	"\x17demo/v1/protected.proto\x12\ademo.v1\x1a\x14auth/v1/access.proto\"\x0f\n" +
	"\rWhoAmIRequest\"\x97\x01\n" +
	"\x0eWhoAmIResponse\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1b\n" +
	"\tissued_at\x18\x03 \x01(\tR\bissuedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\tR\texpiresAt\x12\x1b\n" +
	"\tserved_by\x18\x05 \x01(\tR\bservedBy\"\x12\n" +
	"\x10AdminOnlyRequest\"+\n" +
	"\x11AdminOnlyResponse\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret2\xa1\x01\n" +
	"\x10ProtectedService\x12A\n" +
	"\x06WhoAmI\x12\x16.demo.v1.WhoAmIRequest\x1a\x17.demo.v1.WhoAmIResponse\"\x06\x8a\xb5\x18\x02\b\x01\x12J\n" +
	"\tAdminOnly\x12\x19.demo.v1.AdminOnlyRequest\x1a\x1a.demo.v1.AdminOnlyResponse\"\x06\x8a\xb5\x18\x02\b\x02B\xc1\x01\n" +
	"\vcom.demo.v1B\x0eProtectedProtoP\x01Zegithub.com/Skayfa/reference-patterns/fullstack/auth/paseto-cross-language/issuer-go/pb/demo/v1;demov1\xa2\x02\x03DXX\xaa\x02\aDemo.V1\xca\x02\aDemo\\V1\xe2\x02\x13Demo\\V1\\GPBMetadata\xea\x02\bDemo::V1b\x06proto3"

var (
	file_demo_v1_protected_proto_rawDescOnce sync.Once
	file_demo_v1_protected_proto_rawDescData []byte
)

func file_demo_v1_protected_proto_rawDescGZIP() []byte {
	file_demo_v1_protected_proto_rawDescOnce.Do(func() {
		file_demo_v1_protected_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demo_v1_protected_proto_rawDesc), len(file_demo_v1_protected_proto_rawDesc)))
	})
	return file_demo_v1_protected_proto_rawDescData
}

var file_demo_v1_protected_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_demo_v1_protected_proto_goTypes = []any{
	(*WhoAmIRequest)(nil),     // 0: demo.v1.WhoAmIRequest
	(*WhoAmIResponse)(nil),    // 1: demo.v1.WhoAmIResponse
	(*AdminOnlyRequest)(nil),  // 2: demo.v1.AdminOnlyRequest
	(*AdminOnlyResponse)(nil), // 3: demo.v1.AdminOnlyResponse
}
var file_demo_v1_protected_proto_depIdxs = []int32{
	0, // 0: demo.v1.ProtectedService.WhoAmI:input_type -> demo.v1.WhoAmIRequest
	2, // 1: demo.v1.ProtectedService.AdminOnly:input_type -> demo.v1.AdminOnlyRequest
	1, // 2: demo.v1.ProtectedService.WhoAmI:output_type -> demo.v1.WhoAmIResponse
	3, // 3: demo.v1.ProtectedService.AdminOnly:output_type -> demo.v1.AdminOnlyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demo_v1_protected_proto_init() }
func file_demo_v1_protected_proto_init() {
	if File_demo_v1_protected_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demo_v1_protected_proto_rawDesc), len(file_demo_v1_protected_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo_v1_protected_proto_goTypes,
		DependencyIndexes: file_demo_v1_protected_proto_depIdxs,
		MessageInfos:      file_demo_v1_protected_proto_msgTypes,
	}.Build()
	File_demo_v1_protected_proto = out.File
	file_demo_v1_protected_proto_goTypes = nil
	file_demo_v1_protected_proto_depIdxs = nil
}
