// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file example/v1/newsletter.proto (package example.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file example/v1/newsletter.proto.
 */
export const file_example_v1_newsletter: GenFile = /*@__PURE__*/
  fileDesc("ChtleGFtcGxlL3YxL25ld3NsZXR0ZXIucHJvdG8SCmV4YW1wbGUudjEiQwoQU3Vic2NyaWJlUmVxdWVzdBIWCgVlbWFpbBgBIAEoCUIHukgEcgJgARIXCgRuYW1lGAIgASgJQgm6SAZyBBACGDIiLAoRU3Vic2NyaWJlUmVzcG9uc2USFwoPc3Vic2NyaXB0aW9uX2lkGAEgASgJMl8KEU5ld3NsZXR0ZXJTZXJ2aWNlEkoKCVN1YnNjcmliZRIcLmV4YW1wbGUudjEuU3Vic2NyaWJlUmVxdWVzdBodLmV4YW1wbGUudjEuU3Vic2NyaWJlUmVzcG9uc2UiAELcAQoOY29tLmV4YW1wbGUudjFCD05ld3NsZXR0ZXJQcm90b1ABWnBnaXRodWIuY29tL1NrYXlmYS9yZWZlcmVuY2UtcGF0dGVybnMvZnVsbHN0YWNrL3JwYy9jb25uZWN0LXByb3RvdmFsaWRhdGUtdGFuc3RhY2svc2VydmVyL3BiL2V4YW1wbGUvdjE7ZXhhbXBsZXYxogIDRVhYqgIKRXhhbXBsZS5WMcoCCkV4YW1wbGVcVjHiAhZFeGFtcGxlXFYxXEdQQk1ldGFkYXRh6gILRXhhbXBsZTo6VjFiBnByb3RvMw", [file_buf_validate_validate]);

/**
 * @generated from message example.v1.SubscribeRequest
 */
export type SubscribeRequest = Message<"example.v1.SubscribeRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message example.v1.SubscribeRequest.
 * Use `create(SubscribeRequestSchema)` to create a new message.
 */
export const SubscribeRequestSchema: GenMessage<SubscribeRequest> = /*@__PURE__*/
  messageDesc(file_example_v1_newsletter, 0);

/**
 * @generated from message example.v1.SubscribeResponse
 */
export type SubscribeResponse = Message<"example.v1.SubscribeResponse"> & {
  /**
   * @generated from field: string subscription_id = 1;
   */
  subscriptionId: string;
};

/**
 * Describes the message example.v1.SubscribeResponse.
 * Use `create(SubscribeResponseSchema)` to create a new message.
 */
export const SubscribeResponseSchema: GenMessage<SubscribeResponse> = /*@__PURE__*/
  messageDesc(file_example_v1_newsletter, 1);

/**
 * The proto file is the single source of truth for the contract AND the
 * validation rules: protovalidate constraints below are enforced by the
 * server interceptor, and mirrored by the frontend form schema.
 *
 * @generated from service example.v1.NewsletterService
 */
export const NewsletterService: GenService<{
  /**
   * @generated from rpc example.v1.NewsletterService.Subscribe
   */
  subscribe: {
    methodKind: "unary";
    input: typeof SubscribeRequestSchema;
    output: typeof SubscribeResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_example_v1_newsletter, 0);

