// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=js"
// @generated from file demo/v1/protected.proto (package demo.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_auth_v1_access } from "../../auth/v1/access_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file demo/v1/protected.proto.
 */
export const file_demo_v1_protected: GenFile = /*@__PURE__*/
  fileDesc("ChdkZW1vL3YxL3Byb3RlY3RlZC5wcm90bxIHZGVtby52MSIPCg1XaG9BbUlSZXF1ZXN0ImkKDldob0FtSVJlc3BvbnNlEg8KB3N1YmplY3QYASABKAkSDAoEcm9sZRgCIAEoCRIRCglpc3N1ZWRfYXQYAyABKAkSEgoKZXhwaXJlc19hdBgEIAEoCRIRCglzZXJ2ZWRfYnkYBSABKAkiEgoQQWRtaW5Pbmx5UmVxdWVzdCIjChFBZG1pbk9ubHlSZXNwb25zZRIOCgZzZWNyZXQYASABKAkyvgEKEFByb3RlY3RlZFNlcnZpY2USTQoGV2hvQW1JEhYuZGVtby52MS5XaG9BbUlSZXF1ZXN0GhcuZGVtby52MS5XaG9BbUlSZXNwb25zZSISirUYDgoMcHJvZmlsZS5yZWFkElsKCUFkbWluT25seRIZLmRlbW8udjEuQWRtaW5Pbmx5UmVxdWVzdBoaLmRlbW8udjEuQWRtaW5Pbmx5UmVzcG9uc2UiF4q1GBMKEWFkbWluLmRpYWdub3N0aWNzYgZwcm90bzM", [file_auth_v1_access]);

/**
 * @generated from message demo.v1.WhoAmIRequest
 */
export type WhoAmIRequest = Message<"demo.v1.WhoAmIRequest"> & {
};

/**
 * Describes the message demo.v1.WhoAmIRequest.
 * Use `create(WhoAmIRequestSchema)` to create a new message.
 */
export const WhoAmIRequestSchema: GenMessage<WhoAmIRequest> = /*@__PURE__*/
  messageDesc(file_demo_v1_protected, 0);

/**
 * @generated from message demo.v1.WhoAmIResponse
 */
export type WhoAmIResponse = Message<"demo.v1.WhoAmIResponse"> & {
  /**
   * @generated from field: string subject = 1;
   */
  subject: string;

  /**
   * @generated from field: string role = 2;
   */
  role: string;

  /**
   * RFC 3339, echoed verbatim from the token claims.
   *
   * @generated from field: string issued_at = 3;
   */
  issuedAt: string;

  /**
   * @generated from field: string expires_at = 4;
   */
  expiresAt: string;

  /**
   * Which implementation answered: "go-connect" | "rust-tonic" | "ts-connect".
   *
   * @generated from field: string served_by = 5;
   */
  servedBy: string;
};

/**
 * Describes the message demo.v1.WhoAmIResponse.
 * Use `create(WhoAmIResponseSchema)` to create a new message.
 */
export const WhoAmIResponseSchema: GenMessage<WhoAmIResponse> = /*@__PURE__*/
  messageDesc(file_demo_v1_protected, 1);

/**
 * @generated from message demo.v1.AdminOnlyRequest
 */
export type AdminOnlyRequest = Message<"demo.v1.AdminOnlyRequest"> & {
};

/**
 * Describes the message demo.v1.AdminOnlyRequest.
 * Use `create(AdminOnlyRequestSchema)` to create a new message.
 */
export const AdminOnlyRequestSchema: GenMessage<AdminOnlyRequest> = /*@__PURE__*/
  messageDesc(file_demo_v1_protected, 2);

/**
 * @generated from message demo.v1.AdminOnlyResponse
 */
export type AdminOnlyResponse = Message<"demo.v1.AdminOnlyResponse"> & {
  /**
   * @generated from field: string secret = 1;
   */
  secret: string;
};

/**
 * Describes the message demo.v1.AdminOnlyResponse.
 * Use `create(AdminOnlyResponseSchema)` to create a new message.
 */
export const AdminOnlyResponseSchema: GenMessage<AdminOnlyResponse> = /*@__PURE__*/
  messageDesc(file_demo_v1_protected, 3);

/**
 * ProtectedService is implemented by all three servers (Go, Rust, TS).
 * Each verifies the caller's PASETO access token locally — no call to the
 * issuer — using only the Ed25519 public key. Per-RPC permissions are
 * declared here with (auth.v1.access) and enforced by every server.
 *
 * @generated from service demo.v1.ProtectedService
 */
export const ProtectedService: GenService<{
  /**
   * @generated from rpc demo.v1.ProtectedService.WhoAmI
   */
  whoAmI: {
    methodKind: "unary";
    input: typeof WhoAmIRequestSchema;
    output: typeof WhoAmIResponseSchema;
  },
  /**
   * @generated from rpc demo.v1.ProtectedService.AdminOnly
   */
  adminOnly: {
    methodKind: "unary";
    input: typeof AdminOnlyRequestSchema;
    output: typeof AdminOnlyResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_demo_v1_protected, 0);

