// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/access.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Roles are the closed set of identities; a token carries one role name
// (lower-cased, "user"/"admin"). Permissions are NOT an enum — they are the
// free-form strings the RPCs declare (see AccessRule.permission). Each role
// grants a set of glob patterns over those strings, right here in the
// contract, so a brand-new permission under an existing prefix is covered
// automatically with no edit here.
type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_USER        Role = 1
	// "*" matches everything, including permissions added later.
	Role_ROLE_ADMIN Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_USER",
		2: "ROLE_ADMIN",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_USER":        1,
		"ROLE_ADMIN":       2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_access_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_auth_v1_access_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_access_proto_rawDescGZIP(), []int{0}
}

// Per-RPC ACL, carried by the contract. Default-deny: every method must be
// annotated — public, or with a required permission — and a CI test fails the
// build otherwise.
type AccessRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The permission this RPC requires, e.g. "notes.write". Free-form: the
	// catalogue is just the union of these strings across all RPCs, nothing to
	// maintain on the side. A caller passes if any of its role's grant patterns
	// matches this string.
	Permission string `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	// Explicitly unauthenticated (sign-up, log-in, ...); mounted without the
	// auth interceptor.
	Public        bool `protobuf:"varint,2,opt,name=public,proto3" json:"public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRule) Reset() {
	*x = AccessRule{}
	mi := &file_auth_v1_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRule) ProtoMessage() {}

func (x *AccessRule) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRule.ProtoReflect.Descriptor instead.
func (*AccessRule) Descriptor() ([]byte, []int) {
	return file_auth_v1_access_proto_rawDescGZIP(), []int{0}
}

func (x *AccessRule) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *AccessRule) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

var file_auth_v1_access_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         50002,
		Name:          "auth.v1.grants",
		Tag:           "bytes,50002,rep,name=grants",
		Filename:      "auth/v1/access.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*AccessRule)(nil),
		Field:         50001,
		Name:          "auth.v1.access",
		Tag:           "bytes,50001,opt,name=access",
		Filename:      "auth/v1/access.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// repeated string grants = 50002;
	E_Grants = &file_auth_v1_access_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional auth.v1.AccessRule access = 50001;
	E_Access = &file_auth_v1_access_proto_extTypes[1]
)

var File_auth_v1_access_proto protoreflect.FileDescriptor

const file_auth_v1_access_proto_rawDesc = "" +
	"\n" +
	"\x14auth/v1/access.proto\x12\aauth.v1\x1a google/protobuf/descriptor.proto\"D\n" +
	"\n" +
	"AccessRule\x12\x1e\n" +
	"\n" +
	"permission\x18\x01 \x01(\tR\n" +
	"permission\x12\x16\n" +
	"\x06public\x18\x02 \x01(\bR\x06public*n\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x129\n" +
	"\tROLE_USER\x10\x01\x1a*\x92\xb5\x18\fprofile.read\x92\xb5\x18\anotes.*\x92\xb5\x18\vbookmarks.*\x12\x15\n" +
	"\n" +
	"ROLE_ADMIN\x10\x02\x1a\x05\x92\xb5\x18\x01*:;\n" +
	"\x06grants\x12!.google.protobuf.EnumValueOptions\x18҆\x03 \x03(\tR\x06grants:M\n" +
	"\x06access\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\v2\x13.auth.v1.AccessRuleR\x06accessB\xbe\x01\n" +
	"\vcom.auth.v1B\vAccessProtoP\x01Zegithub.com/Skayfa/reference-patterns/fullstack/auth/paseto-cross-language/issuer-go/pb/auth/v1;authv1\xa2\x02\x03AXX\xaa\x02\aAuth.V1\xca\x02\aAuth\\V1\xe2\x02\x13Auth\\V1\\GPBMetadata\xea\x02\bAuth::V1b\x06proto3"

var (
	file_auth_v1_access_proto_rawDescOnce sync.Once
	file_auth_v1_access_proto_rawDescData []byte
)

func file_auth_v1_access_proto_rawDescGZIP() []byte {
	file_auth_v1_access_proto_rawDescOnce.Do(func() {
		file_auth_v1_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_access_proto_rawDesc), len(file_auth_v1_access_proto_rawDesc)))
	})
	return file_auth_v1_access_proto_rawDescData
}

var file_auth_v1_access_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_v1_access_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_auth_v1_access_proto_goTypes = []any{
	(Role)(0),                             // 0: auth.v1.Role
	(*AccessRule)(nil),                    // 1: auth.v1.AccessRule
	(*descriptorpb.EnumValueOptions)(nil), // 2: google.protobuf.EnumValueOptions
	(*descriptorpb.MethodOptions)(nil),    // 3: google.protobuf.MethodOptions
}
var file_auth_v1_access_proto_depIdxs = []int32{
	2, // 0: auth.v1.grants:extendee -> google.protobuf.EnumValueOptions
	3, // 1: auth.v1.access:extendee -> google.protobuf.MethodOptions
	1, // 2: auth.v1.access:type_name -> auth.v1.AccessRule
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_access_proto_init() }
func file_auth_v1_access_proto_init() {
	if File_auth_v1_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_access_proto_rawDesc), len(file_auth_v1_access_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_auth_v1_access_proto_goTypes,
		DependencyIndexes: file_auth_v1_access_proto_depIdxs,
		EnumInfos:         file_auth_v1_access_proto_enumTypes,
		MessageInfos:      file_auth_v1_access_proto_msgTypes,
		ExtensionInfos:    file_auth_v1_access_proto_extTypes,
	}.Build()
	File_auth_v1_access_proto = out.File
	file_auth_v1_access_proto_goTypes = nil
	file_auth_v1_access_proto_depIdxs = nil
}
