// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Note struct {
	ID        string
	UserID    string
	Text      string
	CreatedAt string
}

type RefreshToken struct {
	ID        string
	UserID    string
	FamilyID  string
	TokenHash string
	CreatedAt string
	ExpiresAt string
	RotatedAt sql.NullString
	RevokedAt sql.NullString
}

type User struct {
	ID           string
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    string
}
