// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createNote = `-- name: CreateNote :exec
INSERT INTO notes (id, user_id, text, created_at) VALUES (?, ?, ?, ?)
`

type CreateNoteParams struct {
	ID        string
	UserID    string
	Text      string
	CreatedAt string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) error {
	_, err := q.db.ExecContext(ctx, createNote,
		arg.ID,
		arg.UserID,
		arg.Text,
		arg.CreatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec

INSERT INTO users (id, email, password_hash, role, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           string
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    string
}

// The store's entire SQL surface. sqlc generates the typed Go methods in
// internal/store/db (committed); store.go wraps them behind domain types.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id = ?
`

func (q *Queries) DeleteNote(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, family_id, token_hash, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertRefreshTokenParams struct {
	ID        string
	UserID    string
	FamilyID  string
	TokenHash string
	CreatedAt string
	ExpiresAt string
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertRefreshToken,
		arg.ID,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const markRotated = `-- name: MarkRotated :execrows
UPDATE refresh_tokens SET rotated_at = ? WHERE id = ? AND rotated_at IS NULL
`

type MarkRotatedParams struct {
	RotatedAt sql.NullString
	ID        string
}

// Conditional rotation is the reuse guard: the row moves out of the
// "pristine" state atomically, and :execrows lets the caller see whether it
// won the race (1) or a concurrent Refresh already rotated it (0).
func (q *Queries) MarkRotated(ctx context.Context, arg MarkRotatedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markRotated, arg.RotatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const noteByID = `-- name: NoteByID :one
SELECT id, user_id, text, created_at FROM notes WHERE id = ?
`

func (q *Queries) NoteByID(ctx context.Context, id string) (Note, error) {
	row := q.db.QueryRowContext(ctx, noteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const notesByUser = `-- name: NotesByUser :many
SELECT id, user_id, text, created_at FROM notes WHERE user_id = ? ORDER BY created_at DESC, id
`

func (q *Queries) NotesByUser(ctx context.Context, userID string) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, notesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteToAdmin = `-- name: PromoteToAdmin :exec
UPDATE users SET role = 'admin' WHERE email = ?
`

func (q *Queries) PromoteToAdmin(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, promoteToAdmin, email)
	return err
}

const refreshTokenByHash = `-- name: RefreshTokenByHash :one
SELECT id, user_id, family_id, token_hash, created_at, expires_at, rotated_at, revoked_at FROM refresh_tokens WHERE token_hash = ?
`

func (q *Queries) RefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, refreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeFamily = `-- name: RevokeFamily :exec
UPDATE refresh_tokens SET revoked_at = ? WHERE family_id = ? AND revoked_at IS NULL
`

type RevokeFamilyParams struct {
	RevokedAt sql.NullString
	FamilyID  string
}

func (q *Queries) RevokeFamily(ctx context.Context, arg RevokeFamilyParams) error {
	_, err := q.db.ExecContext(ctx, revokeFamily, arg.RevokedAt, arg.FamilyID)
	return err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, email, password_hash, role, created_at FROM users WHERE email = ?
`

func (q *Queries) UserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, email, password_hash, role, created_at FROM users WHERE id = ?
`

func (q *Queries) UserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
