// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=js"
// @generated from file auth/v1/access.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { EnumValueOptions, MethodOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file auth/v1/access.proto.
 */
export const file_auth_v1_access: GenFile = /*@__PURE__*/
  fileDesc("ChRhdXRoL3YxL2FjY2Vzcy5wcm90bxIHYXV0aC52MSIwCgpBY2Nlc3NSdWxlEhIKCnBlcm1pc3Npb24YASABKAkSDgoGcHVibGljGAIgASgIKm4KBFJvbGUSFAoQUk9MRV9VTlNQRUNJRklFRBAAEjkKCVJPTEVfVVNFUhABGiqStRgMcHJvZmlsZS5yZWFkkrUYB25vdGVzLiqStRgLYm9va21hcmtzLioSFQoKUk9MRV9BRE1JThACGgWStRgBKjo7CgZncmFudHMSIS5nb29nbGUucHJvdG9idWYuRW51bVZhbHVlT3B0aW9ucxjShgMgAygJUgZncmFudHM6TQoGYWNjZXNzEh4uZ29vZ2xlLnByb3RvYnVmLk1ldGhvZE9wdGlvbnMY0YYDIAEoCzITLmF1dGgudjEuQWNjZXNzUnVsZVIGYWNjZXNzYgZwcm90bzM", [file_google_protobuf_descriptor]);

/**
 * Per-RPC ACL, carried by the contract. Default-deny: every method must be
 * annotated — public, or with a required permission — and a CI test fails the
 * build otherwise.
 *
 * @generated from message auth.v1.AccessRule
 */
export type AccessRule = Message<"auth.v1.AccessRule"> & {
  /**
   * The permission this RPC requires, e.g. "notes.write". Free-form: the
   * catalogue is just the union of these strings across all RPCs, nothing to
   * maintain on the side. A caller passes if any of its role's grant patterns
   * matches this string.
   *
   * @generated from field: string permission = 1;
   */
  permission: string;

  /**
   * Explicitly unauthenticated (sign-up, log-in, ...); mounted without the
   * auth interceptor.
   *
   * @generated from field: bool public = 2;
   */
  public: boolean;
};

/**
 * Describes the message auth.v1.AccessRule.
 * Use `create(AccessRuleSchema)` to create a new message.
 */
export const AccessRuleSchema: GenMessage<AccessRule> = /*@__PURE__*/
  messageDesc(file_auth_v1_access, 0);

/**
 * Roles are the closed set of identities; a token carries one role name
 * (lower-cased, "user"/"admin"). Permissions are NOT an enum — they are the
 * free-form strings the RPCs declare (see AccessRule.permission). Each role
 * grants a set of glob patterns over those strings, right here in the
 * contract, so a brand-new permission under an existing prefix is covered
 * automatically with no edit here.
 *
 * @generated from enum auth.v1.Role
 */
export enum Role {
  /**
   * @generated from enum value: ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ROLE_USER = 1;
   */
  USER = 1,

  /**
   * "*" matches everything, including permissions added later.
   *
   * @generated from enum value: ROLE_ADMIN = 2;
   */
  ADMIN = 2,
}

/**
 * Describes the enum auth.v1.Role.
 */
export const RoleSchema: GenEnum<Role> = /*@__PURE__*/
  enumDesc(file_auth_v1_access, 0);

/**
 * @generated from extension: repeated string grants = 50002;
 */
export const grants: GenExtension<EnumValueOptions, string[]> = /*@__PURE__*/
  extDesc(file_auth_v1_access, 0);

/**
 * @generated from extension: auth.v1.AccessRule access = 50001;
 */
export const access: GenExtension<MethodOptions, AccessRule> = /*@__PURE__*/
  extDesc(file_auth_v1_access, 1);

