// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bookmark/v1/bookmark.proto

package bookmarkv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/Skayfa/reference-patterns/fullstack/auth/paseto-cross-language/issuer-go/pb/auth/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bookmark struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url   string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// RFC 3339.
	CreatedAt     string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bookmark) Reset() {
	*x = Bookmark{}
	mi := &file_bookmark_v1_bookmark_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bookmark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookmark) ProtoMessage() {}

func (x *Bookmark) ProtoReflect() protoreflect.Message {
	mi := &file_bookmark_v1_bookmark_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookmark.ProtoReflect.Descriptor instead.
func (*Bookmark) Descriptor() ([]byte, []int) {
	return file_bookmark_v1_bookmark_proto_rawDescGZIP(), []int{0}
}

func (x *Bookmark) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bookmark) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Bookmark) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Bookmark) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateBookmarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookmarkRequest) Reset() {
	*x = CreateBookmarkRequest{}
	mi := &file_bookmark_v1_bookmark_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookmarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookmarkRequest) ProtoMessage() {}

func (x *CreateBookmarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookmark_v1_bookmark_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookmarkRequest.ProtoReflect.Descriptor instead.
func (*CreateBookmarkRequest) Descriptor() ([]byte, []int) {
	return file_bookmark_v1_bookmark_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookmarkRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateBookmarkRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateBookmarkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookmark      *Bookmark              `protobuf:"bytes,1,opt,name=bookmark,proto3" json:"bookmark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookmarkResponse) Reset() {
	*x = CreateBookmarkResponse{}
	mi := &file_bookmark_v1_bookmark_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookmarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookmarkResponse) ProtoMessage() {}

func (x *CreateBookmarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookmark_v1_bookmark_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookmarkResponse.ProtoReflect.Descriptor instead.
func (*CreateBookmarkResponse) Descriptor() ([]byte, []int) {
	return file_bookmark_v1_bookmark_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBookmarkResponse) GetBookmark() *Bookmark {
	if x != nil {
		return x.Bookmark
	}
	return nil
}

type ListBookmarksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookmarksRequest) Reset() {
	*x = ListBookmarksRequest{}
	mi := &file_bookmark_v1_bookmark_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookmarksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookmarksRequest) ProtoMessage() {}

func (x *ListBookmarksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookmark_v1_bookmark_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookmarksRequest.ProtoReflect.Descriptor instead.
func (*ListBookmarksRequest) Descriptor() ([]byte, []int) {
	return file_bookmark_v1_bookmark_proto_rawDescGZIP(), []int{3}
}

type ListBookmarksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookmarks     []*Bookmark            `protobuf:"bytes,1,rep,name=bookmarks,proto3" json:"bookmarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookmarksResponse) Reset() {
	*x = ListBookmarksResponse{}
	mi := &file_bookmark_v1_bookmark_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookmarksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookmarksResponse) ProtoMessage() {}

func (x *ListBookmarksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookmark_v1_bookmark_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookmarksResponse.ProtoReflect.Descriptor instead.
func (*ListBookmarksResponse) Descriptor() ([]byte, []int) {
	return file_bookmark_v1_bookmark_proto_rawDescGZIP(), []int{4}
}

func (x *ListBookmarksResponse) GetBookmarks() []*Bookmark {
	if x != nil {
		return x.Bookmarks
	}
	return nil
}

type DeleteBookmarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookmarkRequest) Reset() {
	*x = DeleteBookmarkRequest{}
	mi := &file_bookmark_v1_bookmark_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookmarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookmarkRequest) ProtoMessage() {}

func (x *DeleteBookmarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookmark_v1_bookmark_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookmarkRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookmarkRequest) Descriptor() ([]byte, []int) {
	return file_bookmark_v1_bookmark_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteBookmarkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBookmarkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookmarkResponse) Reset() {
	*x = DeleteBookmarkResponse{}
	mi := &file_bookmark_v1_bookmark_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookmarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookmarkResponse) ProtoMessage() {}

func (x *DeleteBookmarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookmark_v1_bookmark_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookmarkResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookmarkResponse) Descriptor() ([]byte, []int) {
	return file_bookmark_v1_bookmark_proto_rawDescGZIP(), []int{6}
}

var File_bookmark_v1_bookmark_proto protoreflect.FileDescriptor

const file_bookmark_v1_bookmark_proto_rawDesc = "" +
	"\n" +
	"\x1abookmark/v1/bookmark.proto\x12\vbookmark.v1\x1a\x14auth/v1/access.proto\x1a\x1bbuf/validate/validate.proto\"a\n" +
	"\bBookmark\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"U\n" +
	"\x15CreateBookmarkRequest\x12\x1c\n" +
	"\x03url\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x10R\x03url\x12\x1e\n" +
	"\x05title\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xc8\x01R\x05title\"K\n" +
	"\x16CreateBookmarkResponse\x121\n" +
	"\bbookmark\x18\x01 \x01(\v2\x15.bookmark.v1.BookmarkR\bbookmark\"\x16\n" +
	"\x14ListBookmarksRequest\"L\n" +
	"\x15ListBookmarksResponse\x123\n" +
	"\tbookmarks\x18\x01 \x03(\v2\x15.bookmark.v1.BookmarkR\tbookmarks\"0\n" +
	"\x15DeleteBookmarkRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02id\"\x18\n" +
	"\x16DeleteBookmarkResponse2\xe4\x02\n" +
	"\x0fBookmarkService\x12p\n" +
	"\x0eCreateBookmark\x12\".bookmark.v1.CreateBookmarkRequest\x1a#.bookmark.v1.CreateBookmarkResponse\"\x15\x8a\xb5\x18\x11\n" +
	"\x0fbookmarks.write\x12l\n" +
	"\rListBookmarks\x12!.bookmark.v1.ListBookmarksRequest\x1a\".bookmark.v1.ListBookmarksResponse\"\x14\x8a\xb5\x18\x10\n" +
	"\x0ebookmarks.read\x12q\n" +
	"\x0eDeleteBookmark\x12\".bookmark.v1.DeleteBookmarkRequest\x1a#.bookmark.v1.DeleteBookmarkResponse\"\x16\x8a\xb5\x18\x12\n" +
	"\x10bookmarks.deleteB\xdc\x01\n" +
	"\x0fcom.bookmark.v1B\rBookmarkProtoP\x01Zmgithub.com/Skayfa/reference-patterns/fullstack/auth/paseto-cross-language/issuer-go/pb/bookmark/v1;bookmarkv1\xa2\x02\x03BXX\xaa\x02\vBookmark.V1\xca\x02\vBookmark\\V1\xe2\x02\x17Bookmark\\V1\\GPBMetadata\xea\x02\fBookmark::V1b\x06proto3"

var (
	file_bookmark_v1_bookmark_proto_rawDescOnce sync.Once
	file_bookmark_v1_bookmark_proto_rawDescData []byte
)

func file_bookmark_v1_bookmark_proto_rawDescGZIP() []byte {
	file_bookmark_v1_bookmark_proto_rawDescOnce.Do(func() {
		file_bookmark_v1_bookmark_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bookmark_v1_bookmark_proto_rawDesc), len(file_bookmark_v1_bookmark_proto_rawDesc)))
	})
	return file_bookmark_v1_bookmark_proto_rawDescData
}

var file_bookmark_v1_bookmark_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bookmark_v1_bookmark_proto_goTypes = []any{
	(*Bookmark)(nil),               // 0: bookmark.v1.Bookmark
	(*CreateBookmarkRequest)(nil),  // 1: bookmark.v1.CreateBookmarkRequest
	(*CreateBookmarkResponse)(nil), // 2: bookmark.v1.CreateBookmarkResponse
	(*ListBookmarksRequest)(nil),   // 3: bookmark.v1.ListBookmarksRequest
	(*ListBookmarksResponse)(nil),  // 4: bookmark.v1.ListBookmarksResponse
	(*DeleteBookmarkRequest)(nil),  // 5: bookmark.v1.DeleteBookmarkRequest
	(*DeleteBookmarkResponse)(nil), // 6: bookmark.v1.DeleteBookmarkResponse
}
var file_bookmark_v1_bookmark_proto_depIdxs = []int32{
	0, // 0: bookmark.v1.CreateBookmarkResponse.bookmark:type_name -> bookmark.v1.Bookmark
	0, // 1: bookmark.v1.ListBookmarksResponse.bookmarks:type_name -> bookmark.v1.Bookmark
	1, // 2: bookmark.v1.BookmarkService.CreateBookmark:input_type -> bookmark.v1.CreateBookmarkRequest
	3, // 3: bookmark.v1.BookmarkService.ListBookmarks:input_type -> bookmark.v1.ListBookmarksRequest
	5, // 4: bookmark.v1.BookmarkService.DeleteBookmark:input_type -> bookmark.v1.DeleteBookmarkRequest
	2, // 5: bookmark.v1.BookmarkService.CreateBookmark:output_type -> bookmark.v1.CreateBookmarkResponse
	4, // 6: bookmark.v1.BookmarkService.ListBookmarks:output_type -> bookmark.v1.ListBookmarksResponse
	6, // 7: bookmark.v1.BookmarkService.DeleteBookmark:output_type -> bookmark.v1.DeleteBookmarkResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_bookmark_v1_bookmark_proto_init() }
func file_bookmark_v1_bookmark_proto_init() {
	if File_bookmark_v1_bookmark_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bookmark_v1_bookmark_proto_rawDesc), len(file_bookmark_v1_bookmark_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bookmark_v1_bookmark_proto_goTypes,
		DependencyIndexes: file_bookmark_v1_bookmark_proto_depIdxs,
		MessageInfos:      file_bookmark_v1_bookmark_proto_msgTypes,
	}.Build()
	File_bookmark_v1_bookmark_proto = out.File
	file_bookmark_v1_bookmark_proto_goTypes = nil
	file_bookmark_v1_bookmark_proto_depIdxs = nil
}
