// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WhoAmIRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WhoAmIResponse {
    #[prost(string, tag="1")]
    pub subject: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub role: ::prost::alloc::string::String,
    /// RFC 3339, echoed verbatim from the token claims.
    #[prost(string, tag="3")]
    pub issued_at: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub expires_at: ::prost::alloc::string::String,
    /// Which implementation answered: "go-connect" | "rust-tonic" | "ts-connect".
    #[prost(string, tag="5")]
    pub served_by: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AdminOnlyRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AdminOnlyResponse {
    #[prost(string, tag="1")]
    pub secret: ::prost::alloc::string::String,
}
include!("demo.v1.tonic.rs");
// @@protoc_insertion_point(module)